<a href="https://colab.research.google.com/github/Ishan2506/Ml_program/blob/main/Mid2_SET2toSET6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#SET1

#SECTION-A

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#Q1
arr = np.random.randint(0, 10, size=(3, 3))
arr

array([[4, 9, 3],
       [6, 0, 9],
       [5, 6, 7]])

In [4]:
#Q2
type(arr)

numpy.ndarray

In [5]:
#Q3
details = {
    'Brand': ['Redmi', 'Apple', 'POCO'],
    'Model': ['Remi A2', 'iPhone 12', 'M4 Pro'],
    'Price': [999, 499, 739]
}
df1=pd.DataFrame(details)
df1

Brand      Model  Price
0  Redmi    Remi A2    999
1  Apple  iPhone 12    499
2   POCO     M4 Pro    739

In [6]:
#Q4
df1['Color'] = ['Black', 'White', 'Grey']
df1

Brand      Model  Price  Color
0  Redmi    Remi A2    999  Black
1  Apple  iPhone 12    499  White
2   POCO     M4 Pro    739   Grey

In [9]:
#SECTION-B

#Q1
df=pd.read_csv('/content/fracture.csv')
df.head(5)

id        age sex     fracture  weight_kg  height_cm      medication  \
0    469  57.052768   F  no fracture       64.0      155.5  Anticonvulsant   
1   8724  75.741225   F  no fracture       78.0      162.0   No medication   
2   6736  70.778900   M  no fracture       73.0      170.5   No medication   
3  24180  78.247175   F  no fracture       60.0      148.0   No medication   
4  17072  54.191877   M  no fracture       55.0      161.0   No medication   

   waiting_time     bmd  
0            18  0.8793  
1            56  0.7946  
2            10  0.9067  
3            14  0.7112  
4            20  0.7909

In [10]:
#Q2
df['bmi'] = df['weight_kg'] / (df['height_cm'] / 100) ** 2
df

id        age sex     fracture  weight_kg  height_cm      medication  \
0      469  57.052768   F  no fracture       64.0      155.5  Anticonvulsant   
1     8724  75.741225   F  no fracture       78.0      162.0   No medication   
2     6736  70.778900   M  no fracture       73.0      170.5   No medication   
3    24180  78.247175   F  no fracture       60.0      148.0   No medication   
4    17072  54.191877   M  no fracture       55.0      161.0   No medication   
..     ...        ...  ..          ...        ...        ...             ...   
164  21892  77.982543   M     fracture       74.0      164.0   No medication   
165  24140  50.285303   F     fracture       59.0      161.0   No medication   
166   6969  46.359721   M     fracture       67.0      169.0   No medication   
167   5505  54.788368   M     fracture       70.0      166.0   No medication   
168     71  69.994822   F     fracture       68.5      165.0   No medication   

     waiting_time     bmd        bmi  
0              18  0.8793  26.467882  
1              56  0.7946  29.721079  
2              10  0.9067  25.111583  
3              14  0.7112  27.392257  
4              20  0.7909  21.218317  
..            ...     ...        ...  
164            49  0.7941  27.513385  
165             6  0.7971  22.761468  
166            10  0.8037  23.458562  
167            14  0.8072  25.402816  
168            25  0.8664  25.160698  

[169 rows x 10 columns]

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
label=LabelEncoder()
df['sex']=label.fit_transform(df['sex'])
df

id        age  sex     fracture  weight_kg  height_cm      medication  \
0      469  57.052768    0  no fracture       64.0      155.5  Anticonvulsant   
1     8724  75.741225    0  no fracture       78.0      162.0   No medication   
2     6736  70.778900    1  no fracture       73.0      170.5   No medication   
3    24180  78.247175    0  no fracture       60.0      148.0   No medication   
4    17072  54.191877    1  no fracture       55.0      161.0   No medication   
..     ...        ...  ...          ...        ...        ...             ...   
164  21892  77.982543    1     fracture       74.0      164.0   No medication   
165  24140  50.285303    0     fracture       59.0      161.0   No medication   
166   6969  46.359721    1     fracture       67.0      169.0   No medication   
167   5505  54.788368    1     fracture       70.0      166.0   No medication   
168     71  69.994822    0     fracture       68.5      165.0   No medication   

     waiting_time     bmd        bmi  
0              18  0.8793  26.467882  
1              56  0.7946  29.721079  
2              10  0.9067  25.111583  
3              14  0.7112  27.392257  
4              20  0.7909  21.218317  
..            ...     ...        ...  
164            49  0.7941  27.513385  
165             6  0.7971  22.761468  
166            10  0.8037  23.458562  
167            14  0.8072  25.402816  
168            25  0.8664  25.160698  

[169 rows x 10 columns]

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x = df[['age', 'sex', 'bmi', 'bmd']].values
y = df['fracture'].values
y=label.fit_transform(y)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
x_train

array([[63.48783737,  1.        , 20.44913742,  0.74089998],
       [80.06020512,  1.        , 23.47928994,  0.67079997],
       [44.68312684,  1.        , 22.64737696,  0.90100002],
       [52.79292063,  1.        , 24.99979708,  0.88880002],
       [60.22138607,  1.        , 34.11235303,  1.0617    ],
       [46.56490164,  0.        , 22.7189744 ,  0.73460001],
       [73.97047074,  0.        , 25.2825699 ,  0.57929999],
       [77.76867742,  0.        , 27.11111111,  0.54189998],
       [88.02415052,  1.        , 22.65573092,  0.62040001],
       [57.05276775,  0.        , 26.46788185,  0.8793    ],
       [72.77238723,  0.        , 36.24120536,  0.509     ],
       [54.77277445,  0.        , 24.8357635 ,  0.79659998],
       [42.81703317,  0.        , 24.5603263 ,  0.88880002],
       [61.64450359,  0.        , 20.95717116,  0.68800002],
       [65.79535204,  0.        , 35.19619501,  0.77380002],
       [69.65373122,  1.        , 29.74419988,  1.0031    ],
       [35.81405763,  1.

In [15]:
from sklearn import svm
model= svm.SVC(kernel='linear')
model.fit(x_train,y_train)
y_pred1=model.predict(x_test)
y_pred1

array([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1])

In [16]:
model.score(x_test,y_test)

0.8823529411764706

In [17]:
#SET3

#SECTION A

#Q1
a = np.arange(0,105,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [18]:
#Q2

np.std(a)

30.276503540974915

In [19]:
#Q3
book_details = {
    'Title': ['Book1', 'Book2', 'Book3'],
    'Author': ['Author1', 'Author2', 'Author3'],
    'Price': [20, 25, 30]
}
df1=pd.DataFrame(book_details)
df1

Title   Author  Price
0  Book1  Author1     20
1  Book2  Author2     25
2  Book3  Author3     30

In [20]:
#Q4
df1.rename(columns={'Price': 'Cost'}, inplace=True)
df1

Title   Author  Cost
0  Book1  Author1    20
1  Book2  Author2    25
2  Book3  Author3    30

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train

array([[62.71790768,  1.        , 30.09143166,  0.8994    ],
       [82.40717913,  1.        , 19.22768787,  0.57209998],
       [44.68312684,  1.        , 22.64737696,  0.90100002],
       [76.94473691,  0.        , 16.01454294,  0.56349999],
       [49.73132379,  0.        , 27.9500393 ,  0.98509997],
       [68.06825266,  0.        , 23.63040123,  0.75089997],
       [64.2131031 ,  1.        , 29.3877551 ,  0.91839999],
       [74.7968828 ,  0.        , 18.75      ,  0.48519999],
       [66.80418542,  1.        , 21.48473615,  0.6882    ],
       [56.18061769,  1.        , 30.45765595,  1.0096    ],
       [54.42421077,  0.        , 26.07897153,  1.0266    ],
       [75.01547985,  1.        , 22.92187461,  0.9364    ],
       [75.7412248 ,  0.        , 29.7210791 ,  0.79460001],
       [79.39970672,  1.        , 29.31985649,  0.9436    ],
       [46.56490164,  0.        , 22.7189744 ,  0.73460001],
       [63.76954463,  0.        , 24.23822715,  0.72149998],
       [83.67835729,  1.

In [22]:
model= svm.SVC(kernel='linear')
model.fit(x_train,y_train)
y_pred2=model.predict(x_test)
y_pred2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1])

In [23]:
model.score(x_test,y_test)

0.7352941176470589

In [24]:
# Section A

#Q1
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5])

In [25]:
#Q2
max_value = np.max(arr)
min_value = np.min(arr)
print("Maximum value:", max_value)
print("Minimum value:", min_value)

Maximum value: 5
Minimum value: 1


In [26]:
#Q3
records = {
    'Name': ['ishan', 'vaibhav', 'naman'],
    'Age': [20, 22, 21],
    'Grade': ['A', 'B', 'C']
}
df1 = pd.DataFrame(records)
df1


Name  Age Grade
0    ishan   20     A
1  vaibhav   22     B
2    naman   21     C

In [32]:
#Q4
df1.drop(columns=['Age'])
df1

Name  Age
0    ishan   20
1  vaibhav   22
2    naman   21

In [33]:
#SECTION B

#Q1
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)


LogisticRegression()

In [35]:
pred=model.predict(x_test)
pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [39]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,pred)

array([[ 1, 11],
       [ 0, 22]])

In [40]:
accuracy_score(y_test,pred)

0.6764705882352942

In [41]:
#SET-5

#SECTION A

#Q1
arr = np.arange(25).reshape(5, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [42]:
#Q2
print("Size of the array:", arr.size)
print("Shape of the array:", arr.shape)

Size of the array: 25
Shape of the array: (5, 5)


In [43]:
#Q3
details = {
    'Brand': ['Redmi', 'Apple', 'POCO'],
    'Model': ['Remi A2', 'iPhone 12', 'M4 Pro'],
    'Price': [999, 499, 739]
}
df1=pd.DataFrame(details)
df1

Brand      Model  Price
0  Redmi    Remi A2    999
1  Apple  iPhone 12    499
2   POCO     M4 Pro    739

In [44]:
df1['Storage'] = ['64GB', '256GB', '128GB']
print(df1)

   Brand      Model  Price Storage
0  Redmi    Remi A2    999    64GB
1  Apple  iPhone 12    499   256GB
2   POCO     M4 Pro    739   128GB


In [45]:
#SECTION B

from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier()
knn_model.fit(x_train, y_train)

KNeighborsClassifier()

In [46]:
y_preds = knn_model.predict(x_test)
accuracy_score(y_test, y_preds)

0.7058823529411765

In [49]:
#SET 6

#SECTION A

#Q1

arr = np.random.rand(10)
print(arr)

[0.92296528 0.48767553 0.40193234 0.41819556 0.52475555 0.95633978
 0.70610492 0.14047174 0.31313293 0.19217353]


In [50]:
#Q2
np.mean(arr)


0.5063747150462444

In [51]:
#Q3
details = {
    'Title': ['The Great Gatsby', 'To Kill a Mockingbird', '1984', 'Pride and Prejudice', 'The Catcher in the Rye'],
    'Author': ['F. Scott Fitzgerald', 'Harper Lee', 'George Orwell', 'Jane Austen', 'J.D. Salinger'],
    'Year': [1925, 1960, 1949, 1813, 1951]
}

df1 = pd.DataFrame(details)
print(df1)

                    Title               Author  Year
0        The Great Gatsby  F. Scott Fitzgerald  1925
1   To Kill a Mockingbird           Harper Lee  1960
2                    1984        George Orwell  1949
3     Pride and Prejudice          Jane Austen  1813
4  The Catcher in the Rye        J.D. Salinger  1951


In [52]:
#Q4
df1.rename(columns={'Year': 'Publication Year'}, inplace=True)
print(df1)

                    Title               Author  Publication Year
0        The Great Gatsby  F. Scott Fitzgerald              1925
1   To Kill a Mockingbird           Harper Lee              1960
2                    1984        George Orwell              1949
3     Pride and Prejudice          Jane Austen              1813
4  The Catcher in the Rye        J.D. Salinger              1951


In [55]:
from sklearn import svm
model= svm.SVC(kernel='linear')
model.fit(x_train,y_train)


SVC(kernel='linear')

In [56]:
y_preds = model.predict(x_test)
accuracy_score(y_test, y_preds)

0.7352941176470589